"""init

Revision ID: 1756762047
Revises:
Create Date: 2025-09-02 00:27:27.538404

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1756762047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('psw_hash', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('name')
                    )
    op.create_table('card',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('board_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('invitation',
                    sa.Column('user_recipient', sa.String(), nullable=False),
                    sa.Column('board_id', sa.Integer(), nullable=False),
                    sa.Column('user_sender', sa.String(), nullable=False),
                    sa.CheckConstraint('user_sender <> user_recipient'),
                    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_recipient'], ['user.name'], ),
                    sa.ForeignKeyConstraint(['user_sender'], ['user.name'], ),
                    sa.PrimaryKeyConstraint('user_recipient', 'board_id')
                    )
    op.create_table('user_board',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('board_id', sa.Integer(), nullable=False),
                    sa.Column('is_owner', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['username'], ['user.name'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('username', 'board_id')
                    )
    op.create_table('comment',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('card_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['author'], ['user.name'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('user_board')
    op.drop_table('invitation')
    op.drop_table('card')
    op.drop_table('user')
    op.drop_table('board')
    # ### end Alembic commands ###
